[supervisord]
nodaemon=true

[program:php-fpm]
command=/usr/local/sbin/php-fpm -F
autorestart=true
priority=10

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autorestart=true
priority=20

[program:python_ml]
command=/root/isystem-1/app/Services/Keuangan/KasDss/python_ml/venv/bin/uvicorn main:app --host 127.0.0.1 --port 8000
directory=/root/isystem-1/app/Services/Keuangan/KasDss/python_ml
autostart=true
autorestart=true
priority=30